[coro_http][fix and ut]Tests for 0382 (#876)

diff --git a/.github/workflows/linux_llvm_cov.yml b/.github/workflows/linux_llvm_cov.yml
--- a/.github/workflows/linux_llvm_cov.yml
+++ b/.github/workflows/linux_llvm_cov.yml
@@ -1,70 +1,108 @@
+#
+# Copyright (c) 2024 Alibaba Group Holding Limited. All Rights Reserved.
+# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
+#
+# This code is free software; you can redistribute it and/or modify it
+# under the terms of the GNU General Public License version 2 only, as
+# published by the Free Software Foundation. Alibaba designates this
+# particular file as subject to the "Classpath" exception as provided
+# by Oracle in the LICENSE file that accompanied this code.
+#
+# This code is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
+# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
+# version 2 for more details (a copy is included in the LICENSE file that
+# accompanied this code).
+#
+# You should have received a copy of the GNU General Public License version
+# 2 along with this work; if not, write to the Free Software Foundation,
+# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
+#
+
 name: Ubuntu 22.04 (llvm cov)
 
 on:
-  pull_request_target:
+  pull_request:
     branches:
       - main
       - fix_coverage_show
+      - 0.3.8.2
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 
 jobs:
-  build:
+  prerequisites:
     runs-on: ubuntu-22.04
-
+    permissions: write-all
+    outputs:
+      id: ${{ steps.get-base-commit.outputs.id }}
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-
-      - name: Install Dependencies
+      - name: 'Get Base Commit id'
+        id: get-base-commit
         run: |
-          sudo apt-get install openssl
-          sudo apt-get install libssl-dev
-          sudo apt-get install llvm
-
-      - name: Install newer Clang
+          sudo apt install -y jq
+          base_commit_id=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | jq -r .base.sha)
+          echo "::set-output name=id::$base_commit_id"
+        shell: bash
+      - name: 'Store Message'
         run: |
-          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
-          sudo apt-get update
-          wget https://apt.llvm.org/llvm.sh
-          chmod +x ./llvm.sh
-          sudo ./llvm.sh 17
-
-      - name: Run Coverage
-        run: |
-          ls
-          cp -r src/coro_rpc/tests/openssl_files .
-          ls
-          mkdir build && cd build
-          CC=clang-17 CXX=clang++-17 cmake .. -DCOVERAGE_TEST=ON -DYLT_ENABLE_SSL=ON
-          make -j
-          export LLVM_PROFILE_FILE="test_ylt-%m.profraw"
-          cd output
-          cd tests
-          ./coro_io_test 
-          ./coro_rpc_test 
-          ./easylog_test 
-          ./struct_pack_test 
-          ./struct_pack_test_with_optimize
-          llvm-profdata merge -sparse test_ylt-*.profraw -o test_ylt.profdata
-          llvm-cov show coro_io_test -object coro_rpc_test -object easylog_test -object struct_pack_test -object struct_pack_test_with_optimize -instr-profile=test_ylt.profdata -format=html -output-dir=../../.coverage_llvm_cov -ignore-filename-regex="thirdparty|asio|src" -show-instantiations=false
-          echo "Done!"
-
-      - name: Upload Coverage Results
-        uses: actions/upload-artifact@v3
+          mkdir -p ./msg
+          echo "action_id=${{github.run_id}}" >> ./msg/action_msg
+          echo "pr_id=${{github.event.pull_request.number}}" >> ./msg/action_msg
+        shell: bash
+      - name: 'Upload Action Message'
+        uses: actions/upload-artifact@v4
         with:
-          name: llvm-cov
-          path: ${{ github.workspace }}/build/.coverage_llvm_cov
+          name: action_msg
+          path: msg/
 
-      - name: Create Code Coverage Report
-        working-directory: ${{github.workspace}}/build/output/tests
-        run: |
-          echo "Code Coverage Report" > tmp.log
-          echo "for detail, [goto summary](https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{github.run_id}}) download Artifacts `llvm-cov`" >> tmp.log
-          echo "\`\`\`" >> tmp.log
-          llvm-cov report coro_io_test -object coro_rpc_test -object easylog_test -object struct_pack_test -object struct_pack_test_with_optimize -instr-profile=test_ylt.profdata -ignore-filename-regex="thirdparty|asio|src" -show-region-summary=false >> tmp.log
-          echo "\`\`\`" >> tmp.log
-
-      - name: Create Comment
-        uses: peter-evans/create-or-update-comment@v2
+  base-cov-test:
+    needs: prerequisites
+    runs-on: ubuntu-22.04
+    outputs:
+      data: ${{ steps.base-cov.outputs.data }}
+    steps:
+      - name: 'Checkout source code'
+        uses: actions/checkout@v4
+      - name: 'Base coverage test'
+        id: base-cov
+        uses: ./.github/actions/coverage
         with:
-          issue-number: ${{ github.event.pull_request.number }}
-          body-file: '${{github.workspace}}/build/output/tests/tmp.log'
+          reset-commit-id: ${{ needs.prerequisites.outputs.id }}
+
+  cov-test:
+    needs: prerequisites
+    runs-on: ubuntu-22.04
+    outputs:
+      data: ${{ steps.cov.outputs.data }}
+    steps:
+      - name: 'Checkout source code'
+        uses: actions/checkout@v4
+      - name: 'Coverage test'
+        id: cov
+        uses: ./.github/actions/coverage
+        with:
+          reset-commit-id: ""
+
+  compare-cov-data:
+    needs:
+      - base-cov-test
+      - cov-test
+    runs-on: ubuntu-22.04
+    steps:
+      - name: 'Compare data'
+        run: |
+            sudo apt install -y bc
+            result=$(echo "${{ needs.cov-test.outputs.data }} > 70" | bc)
+            if [ "$result" -ne 1 ];then
+                echo "coverage cannot be lower than 70%!"
+                exit 1
+            fi
+            result=$(echo "${{ needs.cov-test.outputs.data }} > $(echo "${{ needs.base-cov-test.outputs.data}} * 0.97" | bc)" | bc)
+            if [ "$result" -ne 1 ];then
+                echo "coverage has decreased over 3%!"
+                exit 1
+            fi
+        shell: bash
